import { appSchema, tableSchema } from '@nozbe/watermelondb'

export const databaseSchema = appSchema({
    version: 1,
    tables: [
        tableSchema({
            name: 'users',
            columns: [
                { name: 'name', type: 'string' },
                { name: 'email', type: 'string', isIndexed: true },
                { name: 'total_points', type: 'number' },
                { name: 'level', type: 'number' },
                { name: 'created_at', type: 'number', isOptional: true },
                { name: 'updated_at', type: 'number', isOptional: true },
            ],
        }),
        tableSchema({
            name: 'categories',
            columns: [
                { name: 'name', type: 'string' },
                { name: 'user_id', type: 'string', isIndexed: true },
                { name: 'created_at', type: 'number', isOptional: true },
                { name: 'updated_at', type: 'number', isOptional: true },
            ],
        }),
        tableSchema({
            name: 'habits',
            columns: [
                { name: 'user_id', type: 'string', isIndexed: true },
                {
                    name: 'category_id',
                    type: 'string',
                    isOptional: true,
                    isIndexed: true,
                },
                { name: 'name', type: 'string' },
                { name: 'description', type: 'string', isOptional: true },
                { name: 'frequency_type', type: 'string' },
                { name: 'week_days', type: 'string' },
                {
                    name: 'estimated_duration_minutes',
                    type: 'number',
                    isOptional: true,
                },
                { name: 'preferred_time', type: 'number', isOptional: true },
                { name: 'priority', type: 'string' },
                { name: 'is_focus_of_day', type: 'boolean' },
                { name: 'status', type: 'string' },
                { name: 'seasonal_start', type: 'number', isOptional: true },
                { name: 'seasonal_end', type: 'number', isOptional: true },
                { name: 'created_at', type: 'number', isOptional: true },
                { name: 'updated_at', type: 'number', isOptional: true },
            ],
        }),
        tableSchema({
            name: 'habit_dependencies',
            columns: [
                { name: 'habit_id', type: 'string', isIndexed: true },
                { name: 'trigger_habit_id', type: 'string', isIndexed: true },
                { name: 'type', type: 'string' },
                { name: 'created_at', type: 'number', isOptional: true },
                { name: 'updated_at', type: 'number', isOptional: true },
            ],
        }),
        tableSchema({
            name: 'habit_conditions',
            columns: [
                { name: 'habit_id', type: 'string', isIndexed: true },
                { name: 'condition_habit_id', type: 'string', isIndexed: true },
                { name: 'condition_rule', type: 'string' },
                { name: 'condition_type', type: 'string', isOptional: true },
                { name: 'created_at', type: 'number', isOptional: true },
                { name: 'updated_at', type: 'number', isOptional: true },
            ],
        }),
        tableSchema({
            name: 'events',
            columns: [
                { name: 'user_id', type: 'string', isIndexed: true },
                { name: 'title', type: 'string' },
                { name: 'date_time', type: 'number' },
                { name: 'location', type: 'string', isOptional: true },
                { name: 'recurrence', type: 'string' },
                {
                    name: 'notification_minutes_before',
                    type: 'number',
                    isOptional: true,
                },
                { name: 'countdown_enabled', type: 'boolean' },
                { name: 'conversion_origin', type: 'string' },
                { name: 'created_at', type: 'number', isOptional: true },
                { name: 'updated_at', type: 'number', isOptional: true },
            ],
        }),
        tableSchema({
            name: 'event_subtasks',
            columns: [
                { name: 'event_id', type: 'string', isIndexed: true },
                { name: 'habit_id', type: 'string', isIndexed: true },
                { name: 'due_date', type: 'number', isOptional: true },
                { name: 'created_at', type: 'number', isOptional: true },
                { name: 'updated_at', type: 'number', isOptional: true },
            ],
        }),
        tableSchema({
            name: 'incompletion_reasons',
            columns: [
                { name: 'description', type: 'string' },
                { name: 'created_at', type: 'number', isOptional: true },
                { name: 'updated_at', type: 'number', isOptional: true },
            ],
        }),
        tableSchema({
            name: 'completion_records',
            columns: [
                { name: 'habit_id', type: 'string', isIndexed: true },
                { name: 'date', type: 'number', isIndexed: true },
                { name: 'status', type: 'string' },
                { name: 'completion_time', type: 'number', isOptional: true },
                {
                    name: 'incompletion_reason_id',
                    type: 'string',
                    isOptional: true,
                },
                { name: 'note', type: 'string', isOptional: true },
                { name: 'distraction_lock_enabled', type: 'boolean' },
                { name: 'created_at', type: 'number', isOptional: true },
                { name: 'updated_at', type: 'number', isOptional: true },
            ],
        }),
        tableSchema({
            name: 'streaks',
            columns: [
                { name: 'habit_id', type: 'string', isIndexed: true },
                { name: 'current_streak', type: 'number' },
                { name: 'longest_streak', type: 'number' },
                { name: 'updated_at', type: 'number', isOptional: true },
            ],
        }),
        tableSchema({
            name: 'daily_notes',
            columns: [
                { name: 'user_id', type: 'string', isIndexed: true },
                { name: 'date', type: 'number', isIndexed: true },
                { name: 'text', type: 'string' },
                { name: 'created_at', type: 'number', isOptional: true },
                { name: 'updated_at', type: 'number', isOptional: true },
            ],
        }),
        tableSchema({
            name: 'goals',
            columns: [
                { name: 'habit_id', type: 'string', isIndexed: true },
                { name: 'deadline_type', type: 'string' },
                { name: 'description', type: 'string' },
                { name: 'target_value', type: 'number' },
                { name: 'current_value', type: 'number' },
                { name: 'status', type: 'string' },
                { name: 'created_at', type: 'number', isOptional: true },
                { name: 'updated_at', type: 'number', isOptional: true },
            ],
        }),
        tableSchema({
            name: 'group_consistency_goals',
            columns: [
                { name: 'user_id', type: 'string', isIndexed: true },
                { name: 'target_percentage', type: 'number' },
                { name: 'included_habit_ids', type: 'string' },
                { name: 'period_start', type: 'number' },
                { name: 'period_end', type: 'number' },
                { name: 'created_at', type: 'number', isOptional: true },
                { name: 'updated_at', type: 'number', isOptional: true },
            ],
        }),
        tableSchema({
            name: 'temporary_challenges',
            columns: [
                { name: 'habit_id', type: 'string', isIndexed: true },
                { name: 'duration_days', type: 'number' },
                { name: 'start_date', type: 'number' },
                { name: 'status', type: 'string' },
                { name: 'created_at', type: 'number', isOptional: true },
                { name: 'updated_at', type: 'number', isOptional: true },
            ],
        }),
        tableSchema({
            name: 'rewards',
            columns: [
                { name: 'user_id', type: 'string', isIndexed: true },
                {
                    name: 'goal_id',
                    type: 'string',
                    isOptional: true,
                    isIndexed: true,
                },
                { name: 'description', type: 'string' },
                { name: 'redeemed', type: 'boolean' },
                { name: 'redeemed_at', type: 'number', isOptional: true },
                { name: 'created_at', type: 'number', isOptional: true },
                { name: 'updated_at', type: 'number', isOptional: true },
            ],
        }),
        tableSchema({
            name: 'reminders',
            columns: [
                {
                    name: 'habit_id',
                    type: 'string',
                    isOptional: true,
                    isIndexed: true,
                },
                {
                    name: 'event_id',
                    type: 'string',
                    isOptional: true,
                    isIndexed: true,
                },
                { name: 'type', type: 'string' },
                { name: 'calculated_time', type: 'number', isOptional: true },
                { name: 'geofence_lat', type: 'number', isOptional: true },
                { name: 'geofence_lng', type: 'number', isOptional: true },
                { name: 'geofence_radius_m', type: 'number', isOptional: true },
                { name: 'sent_at', type: 'number', isOptional: true },
                { name: 'created_at', type: 'number', isOptional: true },
                { name: 'updated_at', type: 'number', isOptional: true },
            ],
        }),
        tableSchema({
            name: 'routine_templates',
            columns: [
                { name: 'user_id', type: 'string', isIndexed: true },
                { name: 'name', type: 'string' },
                { name: 'included_habit_ids', type: 'string' },
                { name: 'included_events', type: 'string' },
                { name: 'created_at', type: 'number', isOptional: true },
                { name: 'updated_at', type: 'number', isOptional: true },
            ],
        }),
    ],
})
